local DrRayLibrary = loadstring(game:HttpGet("https://raw.githubusercontent.com/GhostQut/FreemUI-V2/main/Source.lua"))()

local window = DrRayLibrary:Load("Anime Defenders", "Default")

local tab1 = DrRayLibrary.newTab("Main", "")
local tab2 = DrRayLibrary.newTab("SetUp", "")
local tab3 = DrRayLibrary.newTab("Summon", "")
local tab4 = DrRayLibrary.newTab("Misc", "")
local tab6 = DrRayLibrary.newTab("Other", "")

local codes = {
    
}

tab3.newButton("Redeem ALL Codes", "", function()
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("thanks500k")
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("MEMBEREREBREWRERES")
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("raidsarecool")
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("sorry4delay")
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("dayum100m")
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("wsindach4ht")
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("200kholymoly")
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("adontop")
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("subcool")
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("sub2toadboigaming")
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("sub2jonaslyz")
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("sub2riktime")
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("sub2mozking")
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("sub2karizmaqt")
    task.wait(.1)
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("sub2nagblox")
end)