local DrRayLibrary = loadstring(game:HttpGet("https://raw.githubusercontent.com/GhostQut/FreemUI-V2/main/Source.lua"))()

local window = DrRayLibrary:Load("Anime Defenders", "Default")

local tab1 = DrRayLibrary.newTab("Main", "")
local tab2 = DrRayLibrary.newTab("SetUp", "")
local tab3 = DrRayLibrary.newTab("Summon", "")
local tab4 = DrRayLibrary.newTab("Misc", "")
local tab6 = DrRayLibrary.newTab("Other", "")

tab3.newButton("Redeem ALL Codes", "", function()
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("thanks500k")
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("MEMBEREREBREWRERES")
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("raidsarecool")
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("sorry4delay")
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("dayum100m")
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("wsindach4ht")
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("200kholymoly")
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("adontop")
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("subcool")
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("sub2toadboigaming")
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("sub2jonaslyz")
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("sub2riktime")
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("sub2mozking")
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("sub2karizmaqt")
    game:GetService("ReplicatedStorage").Remotes.UseCode:InvokeServer("sub2nagblox")
end)